import { useRef, useEffect } from "react";
import Head from "next/head";
import { EditorState } from "@codemirror/state";
import {EditorView, basicSetup} from "codemirror"
import styles from "../../styles/CodeMirror.module.css";

export default function CodeMirror() {
  const editorEl = useRef(null);
  const editor = useRef(null);

  useEffect(() => {
    if (editor.current) return;
    let startState = EditorState.create({
      doc: "Select * from milvus.collection",
      extensions: [basicSetup],
    });

    editor.current = new EditorView({
      state: startState,
      parent: editorEl.current,
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Codemirror editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>codemirror</h1>
        <div ref={editorEl}></div>
      </main>
    </div>
  );
}
