// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Restful = 2,
  Rest = 3,
  VERB = 4,
  URL = 5,
  Keyword = 6,
  Identifier = 7,
  Action = 8,
  Query = 9
